
spring:
  application:
    name: duoduo-web
  datasource:
    druid:
      url: jdbc:mysql://59783869de818.gz.cdb.myqcloud.com:5211/doudou_new?characterEncoding=utf-8&serverTimezone=GMT%2B8
      password: ERqIJmLaFXp/jSG1b/8uYBY80EVuQHAhVeM5HKl9yEKJcGEbaJJv3qFGdKA6KLomSxlpgMQI3mMpaZLzLZErWA==
      username: bNVOqb7WKLX5Bjnw+LMv92taj25KOxDimXxILPQjw42wgv+1lHzOH8kr97xDwWdhpY67QuYCS7sWN4W46YbkFA==
  ## 阿里云服务器已经安装了redis
  redis:
    host: 47.104.239.91
    port: 6389
    password: ENC(d2TAJ5KAGuWizyT44Q6/TfJjUkoH+a6YQaCukJt9uvQ=)
    database: 1

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

wechat:
  wxa:
    app-id: ENC(LfWpZa/xvKC6s7RCSw4ltPEek+EGJq2H9oV5cDogT/T0KqVQtUKnmQ==)
    app-secret: ENC(VGtOzcpTLCmxWhY4BimLp0dCXdTTyrU2Cpzl6HPWwcQD1svAknzscklRgfDW+zYNSVv8BfMHmzI=)
    login-url: https://api.weixin.qq.com/sns/jscode2session?appid=%s&secret=%s&js_code=%s&grant_type=authorization_code
    access-token-url: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=%s&secret=%s
    paid-union-id-url: https://api.weixin.qq.com/wxa/getpaidunionid?access_token=%s&openid=%s

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.doudou.dao.entity
  global-config:
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
    db-config:
      #全局默认主键类型 AUTO:"数据库ID自增", NONE:"该类型为未设置主键类型(将跟随全局)", INPUT:"用户输入ID",
      # ID_WORKER:"全局唯一ID (idWorker)", UUID:"全局唯一ID (UUID)", ID_WORKER_STR:"字符串全局唯一ID (idWorker 的字符串表示)"
      id-type: AUTO
      #逻辑已删除值,(逻辑删除下有效)
      logic-delete-value: 0
      #逻辑未删除值,(逻辑删除下有效)
      logic-not-delete-value: 1


local:
  file:
    path: image
    dir: /Users/liwei/studySpace/doudou/doudou-wx-api/src/main/resources/file

admin:
  audit:
    url: http://127.0.0.1:8081/api/admin/resource/audit

server:
  port: 8082
